### ISSUE TITLE
How to setup a mutation ?

### ISSUE THREAD

**Issue by rogergl** [grooviter/gql#17]
I tried the following but that gives:

> caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'gql.dsl.ObjectTypeBuilder$FieldBuilder@70cd3ca8' with class 'gql.dsl.ObjectTypeBuilder$FieldBuilder' to class 'graphql.schema.GraphQLArgument$Builder'
> 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
> 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
> 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
> 	a

```
 def DATA = [
            [date   : '2017-10-10',
             title  : 'Total Recording',
             entries: 159,
             comment: 'only get calls'],
            [date   : '2017-05-10',
             title  : 'Total Recording',
             entries: 19,
             comment: 'only get calls'],
    ]
    def GraphQLHistory = DSL.type('History') {
        field 'date', GraphQLString
        field 'title', GraphQLString
        field 'entries', GraphQLInt
        field 'comment', GraphQLString
    }

    def schema = DSL.schema {
        queries {
            field('history') {
                type list(GraphQLHistory)
                fetcher { env -> return historyCollection.all() }
            }
        }
        mutations {
            field('insertHistory') {
                type GraphQLHistory
                fetcher {env ->
                    def item = env.arguments.item
                    println(item)
                    return DATA[0]
                }
                argument('item') {
                    type GraphQLHistory
                }
            }
        }
    }
```

**Comment by rogergl** [comment]
Ok seems I have to create a special input type.

**Comment by mariogarcia** [comment]
Mmmmm interesting, I think I should add some type checking help to improve error feedback. Although you've seen it quickly however the error message is really ugly.

**Comment by mariogarcia** [comment]
Ok, I've checked the issue twice, and it seems the `type` method is ambiguous, specially if you're using an IDE. If you're using an IDE the auto-completion shows two `type(...)` methods and the user should only be using the `type(inputtype)` inside the `argument('name').

That's something difficult to fix, because the way the DSL works it can't hide the upper `type(xxx)` used in the `field` node.

So, I'm considering two options:

- **Renaming the `type` method** inside the DSL and be more explicit about the type of the type method XD. That would mean having different methods depending on whether we're setting a field type or an input type:

```groovy
def schema = DSL.schema {
  queries {
    field('history') {
      fieldType list(GraphQLHistory)
      fetcher { env -> return historyCollection.all() }
    }
  }
  mutations {
    field('insertHistory') {
      fieldType GraphQLHistory
        fetcher {env ->
          def item = env.arguments.item
            println(item)
            return DATA[0]
          }
        argument('item') {
          inputType GraphQLHistory
        }
      }
    }
}
```
This wouldn't avoid the fact that the `fieldType` will be still available in the `argument` node, but I guess it's more clear it doesn't belong to that node, and you shouldn't use it there.

- **Removing the `type` method**: including the types as the signature of the upper node, removing the `type` method completely:

```groovy
def schema = DSL.schema {
  queries {
    field('history', list(GraphQLHistory)) {
      fetcher { env -> return historyCollection.all() }
    }
  }
  mutations {
    field('insertHistory', GraphQLHistory) {
        fetcher {env ->
          def item = env.arguments.item
            println(item)
            return DATA[0]
          }
        argument('item', GraphQLHistory) {
          description 'argument description' 
        }
      }
    }
}
```
I guess the bottom line is to avoid ambiguity to avoid frustration among DSL users. What do you think ?  :smile:

**Comment by rogergl** [comment]
I like the second approach.  One more thing. I suppose that the concept of type and input is from GraphQL? Do you know the rationale behind this decision ?

**Comment by mariogarcia** [comment]
Nope, but I guess they needed to map 1-1 GraphQL spec to Java types and maybe that's why they decided to have a specific type for input types.

**Comment by mariogarcia** [comment]
BTW I've come to a solution about the problem we had at hand. In the end is a solution between the two we were considering. I'll try to explain why:

The solution is to remove the posibility of using `type TYPE` call inside the `arguments { }` scope:

```groovy
field('name') {
  type MyOutputTypeOrScalar

  argument('argumentName', InputOrScalarType) {
    description 'description'
  }
}
```
- The DSL won't let u use the field `type` inside the argument closure. Then there is no chance to think it may work for argument
- The only way to specify the type for an argument is to add it as second parameter

I didn't want to add the second parameter to `field(name, type)` because that wouldn't respect an important feature the DSL has which is, you don't have to import any `graphq-java` scalar type to use it within the DSL.

I've also overloaded `argument` to allow a one-line argument declaration without setting the description:

```groovy
field('name') {
  type MyOutputTypeOrScalar

  argument 'argumentName', InputOrScalarType
}
```

Regards
Mario
